apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

replicas:
  - name: moathclinic-app
    count: 1

images:
  - name: moathclinicacr.azurecr.io/moathclinic-app
    newTag: __IMAGE_TAG__
